### PR TITLE
README provided by erasche (Thanks!)

### PR DESCRIPTION
**Pull request by scottcain**
This takes the place of this pull request: https://github.com/GMOD/Chado/pull/22 where @erasche also suggested getting rid of the "other" files in the Chado repo.  While this is a laudable goal, I don't want to just delete everything, so that's not going to happen right now.

### CODE REVIEW

**Comment by erasche** [comment]
awesome :) I figured it was too wide-reaching of a change, but I was hopeful.

**Comment by scottcain** [comment]
Thanks again--I do want to do much of the reorganization that you did in the other commits in that pull request, but the GMODTools directory should probably moved to it's own repo first (which will take a small amount of time, so naturally, I'll put it off for now :-)

**Comment by erasche** [comment]
If you create a repo for it, and give me push access (free to remove afterwards), I'll happily do the extraction / git history filtering for you and push it when I'm back to work on the 18th ;)

**Comment by erasche** [comment]
Forgot [how easy it was](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) @scottcain, I had mis-remembered and thought you needed to use [`bfg`](https://rtyley.github.io/bfg-repo-cleaner/) for the cleaning or something. Anyway, I [went ahead and did that and pushed the result here](https://github.com/erasche/GMODTools). Happy to have this transferred to the gmod project. I've added you in the repo (you'll need to [accept the invite](https://github.com/erasche/GMODTools/invitations) first before I can make you an admin and give you permission to migrate it at your leisure.) If you want GMODTools removed completely from chado's history, then that would require the `bfg` and rewriting of history. However we can just delete the directory and be done with it. I've [opened a PR to that effect](https://github.com/GMOD/Chado/pull/60)

Hope this helps!

**Comment by erasche** [comment]
Ok, I decided it was silly to wait, so I went ahead and did the others as well. Please find them below. I've issued invitations to you on all, whenever you accept I'll make sure you have permissions to transfer the repository to the GMOD organisation since I don't have that ability.

- https://github.com/erasche/chado-hackathon2007
- https://github.com/erasche/chado-javatools
- https://github.com/erasche/chado-xmltools

I'll leave it up to you to remove all the folders from the parent Chado repository as and when you like.

**Pull request merged**
