### PR TITLE
Issue 65 - search_path issue with binloc functions used for featureloc indices

### PR DESCRIPTION
**Pull request by jogoodma**
Here is a PR for the issue.  I'd greatly appreciate some extra eyes on this as we don't really utilize these indices so I've only done rudimentary checks to look for issues caused by this change.  I'm also not very familiar with the Chado build process and may have overlooked necessary edits.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
hello,

looking at this PR I can see that it hs a lot of additional changes in addition to issue #65 (namely cvalue_id added to the props).    Am i correct that its really just the changes to `chado/modules/cv/functions/fill_cvtermpath.plpgsql`  and `chado/modules/sequence/functions/range.plpgsql` ?

With the new flyway migration setup, we just need an SQL script altering those functions.

**Comment by spficklin** [comment]
Just to ping this one again... what needs to be done to get this moving along (aside from resolving the current merge conflict)?

**Comment by jogoodma** [comment]
@bradfordcondon I'm not sure how the other changes got lumped into this PR.  Perhaps I botched something when I did the branch / PR.  I don't recall seeing the other changes after I initially made the PR.  Regardless, the only changes needed are in 032d736470f445c9bf00e0c8cc8e6536eeb7b255.

Should I start over from a new branch of 1.4, add these changes as a flyway migration script, and then do a new PR?

**Comment by bradfordcondon** [comment]
>Should I start over from a new branch of 1.4, add these changes as a flyway migration script, and then do a new PR?


Yes I think that would be the simplest solution, thanks!

**Comment by jogoodma** [comment]
Closing this PR in favor of #105

**Pull request closed without merging**
