### PR TITLE
PR Guidelines (1st stage of governance)

### PR DESCRIPTION
**Pull request by laceysanderson**
Issue #63 

This PR adds our discussion in Issue #63 and corresponding google doc into our ReadtheDocs making it official and binding. I tried to capture the meaning of the google doc while formalizing the language and would appreciate a careful reading by the @GMOD/chado-pmc. To make this easier I have added a series of screenshots demonstrating the rendered docs:

docs-1
docs-2
docs-3

### CODE REVIEW

**Comment by spficklin** [comment]
Thanks Lacey for putting this together!  My only suggestion would be to adjust this sentence a bit: "However, they are still very subjective and any disputes to..." .   Maybe something like:
"However, they are not yet complete or exhaustive and may change as  Chado governance evolves.  Any discussion regarding these levels of "changes"  is welcome, can be suggested by anyone, must be discussed on the GitHub issue queue and voted on by the PMC."

**Comment by laceysanderson** [comment]
Thanks for the suggestion @spficklin! I've updated it to:

> The following definitions attempt to provide guidance as to the magnitude of the change to the Chado database through providing examples. However, they are not yet complete or exhaustive and may change as Chado governance evolves. If your change does not align with any of these examples, please justify where you feel it fits in the PR and the Chado PMC will vote based on that information.

**Comment by scottcain** [comment]
Hmm, what about the event when a member of the PMC submits a pull request for a large change, and all of the other members of the PMC approve.  You're still short one review...

**Comment by laceysanderson** [comment]
Hmmm... good point. Then someone from the community needs to review as well. This would ensure it is supported by the community and that someone at least needs it enough to review 🤷‍♀️ 

Alternatively, we could change it to 5+ reviews but IMO that brings it too close to a medium change and makes it to easy to incorporate.

**Comment by scottcain** [comment]
@laceysanderson I think that's the right answer too--it means somebody else has to think it's a good idea too, and that shouldn't be unreasonable for a large change.

**Comment by guignonv** [comment]
@laceysanderson May I ask (for my personal knowledge) why is it requested to have an issue open for 2 weeks before creating a pull request? I ask the question because I often open an issue and then a couple of hours or days after, I put an associated PR to solve the problem. Sometimes I even don't submit an issue and just put a PR. So this rule would mean that I shouldn't provide a PR before 2 weeks after posting an issue to the queue? Or maybe I understand it wrong... :-S

**Comment by scottcain** [comment]
Hi Valentin, 

What is intended is that the issue be open at least two weeks before a pull request is merged, to make sure there is adequate time to discuss it. If that’s not clear, it should be clarified. 

Thanks,
Scott

**Comment by bradfordcondon** [comment]
>I ask the question because I often open an issue and then a couple of hours or days after, I put an associated PR to solve the problem.

@guignonv this is fine for "self evident" bugs and fixes. That said, even fixes require people to wrap their head around the fix, and determine that said fix wouldn't conflict with their site.  That's why we want to wait two weeks, even in the case of a bug fix.  For an addition to Chado, the reason should be more clear- we need to give the community time to evaluate and object.

That said, issue #96 and its associated PR #99 are an example of where we didn't wait two week: it was an obvious bug to not support an older postgres version and we needed to fix ASAP.  Such exceptions should always be the minority, though.

**Comment by guignonv** [comment]
Thanks guys for the clarification. :-) I guessed it was to let people have time to react but that makes it clear it's not for other reasons.

However, what needs to be clarified for me is (I rephrase my question): "If we provide a PR, do we have to also open an issue related to that PR?" Maybe a PR opened and not merged for 2 weeks would be sufficient? Or is it required because people might not look into PR but rather into the issue queue?

**Comment by bradfordcondon** [comment]
My question to you @guignonv is why are you providing a PR without checking in with the community first? Chado is agreed upon community schema.  Trying to make changes to it without seeking input or consensus just isn't a good idea, because you're also making changes to everyone else's database!  If the PR is only for the documentation, that might be a good reason why and I have no problem with that. 
My personal opinion is its helpful to keep issue and pr discussion separate, so that issues can revolve around "is this a good idea for everyone", and pr's can center on "does this PR do what we all agreed upon".

In this issue's, we've gotten our 6 reviews and the PR can be merged.  I'll wait until next week before doing so in case anyone disagrees with me.

**Comment by guignonv** [comment]
@bradfordcondon  Yup, you're right! Here we're talking about a database and not just code with bugs/missing features so it's a bit different from what I would do in other projects. What you're saying makes sens, people would check issues (in a "forum" way) and not PR. :-) Posting an issue first and attaching a PR after, ok for me. :)

**Pull request merged**
