### PR TITLE
Fixing foreign key for db_relationship type_id

### LINKED ISSUE #117: db_relationship type_id should be foreign key pointing to cvterm not db table
Hello,

Right now the creation of the db_relationship table is:

create table db_relationship (
    db_relationship_id bigserial not null,
    type_id bigint not null,
    subject_id bigint not null,
    object_id bigint not null,
    primary key (db_relationship_id),
    foreign key (type_id) references db (db_id) on delete cascade INITIALLY DEFERRED,
    foreign key (subject_id) references db (db_id) on delete cascade INITIALLY DEFERRED,
    foreign key (object_id) references db (db_id) on delete cascade INITIALLY DEFERRED,
    constraint db_relationship_c1 unique (subject_id,object_id,type_id)
);

but it make sense to change the type_id reference to be the same as in the sequence module:

create table db_relationship (
    db_relationship_id bigserial not null,
    type_id bigint not null,
    subject_id bigint not null,
    object_id bigint not null,
    primary key (db_relationship_id),
    foreign key (type_id) references cvterm (cvterm_id) on delete cascade INITIALLY DEFERRED,
    foreign key (subject_id) references db (db_id) on delete cascade INITIALLY DEFERRED,
    foreign key (object_id) references db (db_id) on delete cascade INITIALLY DEFERRED,
    constraint db_relationship_c1 unique (subject_id,object_id,type_id)
);

Hope it can help :)

### PR DESCRIPTION
**Pull request by scottcain**
Per #117 , the type_id should point at the cvterm table, no the db table.

### CODE REVIEW

**Comment by scottcain** [comment]
Definitely a small change, so a 2 person review team should certainly be sufficient.

**Review by laceysanderson — APPROVED** [review]
Yes, looks perfect @scottcain  👍 Good catch @dreyes17!

**Comment by spficklin** [comment]
This PR is still not quite right and it failed a flyway migrate test.

Here's the problem:

```sql
foreign key (type_id) references db (cvterm_id) on delete cascade INITIALLY DEFERRED,
```
it should be:
```sql
foreign key (type_id) references cvterm (cvterm_id) on delete cascade INITIALLY DEFERRED,
```
I've fixed the PR and run Flyway on it and now it works and can be merged

```
Database: jdbc:postgresql://localhost:5432/chado (PostgreSQL 12.9)
Current version of schema "public": 1.3.3.001
Migrating schema "public" to version "1.3.3.002 - add db relationship table"
Migrating schema "public" to version "1.3.3.003 - alter analysis unique constraint"
Migrating schema "public" to version "1.3.3.004 - add synoynm indices cvtermsynonym"
Migrating schema "public" to version "1.3.3.005 - add type id 2 project table"
Migrating schema "public" to version "1.3.3.006 - modify mage"
Migrating schema "public" to version "1.3.3.007 - fix search path"
```

**Review by spficklin — APPROVED** [review]

**Comment by laceysanderson** [comment]
Further discussion on this while testing #129 made us realize that this should be a new migration rather than fix an existing one. The idea with flyway is that people can use it to get access to updates to the schema before an official release is made. By altering an existing migration, people only get the fix if they hadn't applied the previous migration... so instead, we should make a new one just to be safe.

**Comment by laceysanderson** [comment]
Removed myself from review since I've now made significant changes 😬 @scottcain do you agree with the new approach?

**Comment by spficklin** [comment]
Since this is a small change PR and you only made other small changes @laceysanderson I propose that we just all do another round of checks rather than you bowing out of review.... just my two cents.

**Pull request merged**
