### PR TITLE
GitHub workflows to help with review

### LINKED ISSUE #142: Github Workflows to help with Review
We haven't had a lot of time to reviews and there have been instances of errors sneaking in because of this. I think some automated testing workflows would greatly alleviate this as it would ensure we don't have to manually test but can rather do a code review and that is enough.

Also, it would allow us to test on multiple postgresql versions which is currently missing.

### PR DESCRIPTION
**Pull request by laceysanderson**
Issue #142 

## Description

This PR does the following things:

- [x] Update docker to use the most recent version of Ubuntu + Flybase.
- [x] Update docker to act on the current directory/branch rather then pulling from github.
- [x] Create basic Github workflow that will run the flyway migrations.
- [x] Fix the syntax errors in through V1.3.3.011 migrations that snuck through 🙈 
- [x] Update dockerfile to take PostgreSQL version as an arguement.
- [x] Matrix the workflow to run migrations on each version of PostgreSQL supported.
- [x] Create Github Workflow to build docker images and push to github so we can just pull when wanting to test.
- [x] Update or remove the makefile as it currently operates based on the old dockerfile setup.
- [x] Update Readme with new docker instructions.

## Testing

1. Confirm the automated testing runs and passes.
2. Clone this directory locally and test building docker images, running containers and using flyway (more instructions below).
3. Try pulling the existing images on the container registry and playing with them. [See this in the new README here](https://github.com/GMOD/Chado/tree/142-github-workflows-to-help-with-review?tab=readme-ov-file#using-the-chado-docker-image).

When you build the image using the new dockerfile, it actually uses the current code in your Chado clone. In order to allow you to modify the migrations while running the container, you will mount your current directory inside the container using the following approach. This way you can edit the files locally and they will be automatically updated within the container and available to flyway.

```bash
git clone https://github.com/GMOD/Chado chado-142-dockerUpgrades
cd chado-142-dockerUpgrades
git checkout 142-github-workflows-to-help-with-review
docker build --tag gmod/chado:local --file docker/Dockerfile \
    --build-arg PGSQL_VERSION=<version> ./
docker run -it -rm --volume=$(pwd):/Chado gmod/chado:local
```
Replace the `<version>` with the version of postgresql you want installed. This can be one of 12, 13, 14, 15, or 16; the default is 16 if the build-arg is not specified.

Note: You should not go into the docker directory but rather stay in the root of the clone.

You can test FlyWay migrations by running these flyway commands:

   - See what migrations need to be applied:

   ```bash
   flyway info
   ```

   - Run the migrations available:
   ```bash
   flyway migrate
   ```
The migrations have been applied correctly if you do not see any red errors. However, it is good practice to run flyway info again to confirm.

### CODE REVIEW

**Comment by spficklin** [comment]
@laceysanderson this worked just fine for me.  I love having this testing for a PR via Docker.

It's been so long since I've used Flyway that I'm having to reorient myself to it and I have one question about the migrations in this test.  Can you you remind me where these are coming from?  I'm assuming that if this were a real PR with suggested changes to Chado that the migrations would come from within the PR.  When this gets merged will the migrations in this test get merged too?

**Comment by laceysanderson** [comment]
Thanks for the review @spficklin! All the migrations in this PR are ones already existing in the 1.4 branch (other merged PRs :-) ). That said, this one does make a small change to the last migration as it was actually not able to be applied 🙈 

Each PR will add a new migration to the current list and then they will all be applied in order. We'll keep this up with the list of migrations growing until we release a formal 1.4 at which point all the existing migrations will be applied, the new schema dumped and then we can start fresh with the numbering :-)

**Comment by spficklin** [comment]
Understood. Thanks for that reminder.  Yes, this worked great for me. I approve the PR.

**Review by spficklin — APPROVED** [review]

**Review by scottcain — APPROVED** [review]
I don't have the bandwidth at the moment to try running these changes, but it feels like a really good idea, so I approve too.

**Comment by laceysanderson** [comment]
Thank you both! 🎉 ❤️

**Pull request merged**
