### PR TITLE
Move ddl2modules

### PR DESCRIPTION
**Pull request by spficklin**
Created the new db module for the db and dbxref tables.  I added a new directory and moved the views and function files.  Please check to make sure I did this correctly.

### CODE REVIEW

**Comment by spficklin** [comment]
Oopps... closing this.  Need to merge with 1.3 branch not master

**Comment by scottcain** [comment]
I hate when I do that :-)

**Comment by scottcain** [comment]
Also, it seems like most people will do one pull request per branch and then delete the branch after it gets merged.  I don't suppose it matters, but then, maybe it does, since that's what people seem to do :-)

**Comment by spficklin** [comment]
Okay, I'll delete it and create a new one.

**Pull request closed without merging**
