### PR TITLE
changes to mage (migration V1.3.3.006)

### PR DESCRIPTION
**Pull request by srobb1**
rewrote  https://github.com/GMOD/Chado/pull/50/files

### CODE REVIEW

**Comment by spficklin** [comment]
@srobb1 before we can review this it needs to be linked to an issue.  Is there an issue already submitted for the changes in this PR?

**Comment by scottcain** [comment]
I'm kind of inclined to just pull in this PR even though it isn't linked to an issue.  I'm going to add my accepting review, and poke @spficklin to see if he wants to do the same.

**Review by scottcain — APPROVED** [review]
👍

**Review by spficklin — APPROVED** [review]

**Comment by laceysanderson** [comment]
We have 5 approvals so I'm going to merge :-)

**Pull request merged**
