### PR TITLE
Docker updates

### LINKED ISSUE #128: Update Docker Image for Flyway
To help make testing of PRs a bit easier the Chado Docker image should be integrated with flyway.

### PR DESCRIPTION
**Pull request by spficklin**
Issue: #128 

This PR updates the docker image provided by this repository to:
- Include Flyway. 
- Adds a default password be set for the postgres user, which is hardcoded in the `Dockerfile` and `flyway.conf` files.  This is necessary because flyway cannot connect via the UNIX socket. 
- I added a message of the day `motd` that warns the user not to use this for production (See below)
- I added an `entryfile` script that runs the postgresql server and drops the user to a bash shell.
- Updates to the README
- A makefile to automatically build the images

To Test
=====
Build the docker image using the new makefile
```bash
cd docker
make v1.31
```
Startup the image:
```bash
docker run -it gmod/chado:1.31
```

To test Flyway changes, change Chado to use the 1.4 branch
```bash
cd /Chado/
git checkout 1.4
```

Run Flyway from the root directory:
```bash
flyway info
flyway baseline
flyway migrate
```

Examples
======
The warning message when the image first starts:

```
* Starting PostgreSQL 12 database server                                                                                                                                                                            [ OK ] 
Ubuntu 20.04.4 LTS \n \l

   ________  _____    ____  ____
  / ____/ / / /   |  / __ \/ __ \
 / /   / /_/ / /| | / / / / / / /
/ /___/ __  / ___ |/ /_/ / /_/ /
\____/_/ /_/_/  |_/_____/\____/

This Chado docker image uses default security settings for
PostgreSQL and has a hard-coded password for the postgres
user.  Do not use this image for a production service without
first correcting

```

Example usage of the `flyway info` command:

```bash
root@da57899c2665:/# flyway info
Flyway is up to date
38 SQL migrations were detected but not run because they did not follow the filename convention.
If this is in error, enable debug logging or 'validateMigrationNaming' to fail fast and see a list of the invalid file names.
Flyway Community Edition 8.5.2 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.2

Database: jdbc:postgresql://localhost:5432/chado (PostgreSQL 12.9)
Schema version: << Empty Schema >>

+-----------+-----------+-----------------------------------+------+--------------+---------+
| Category  | Version   | Description                       | Type | Installed On | State   |
+-----------+-----------+-----------------------------------+------+--------------+---------+
| Versioned | 1.3.3.001 | add stock biomat table            | SQL  |              | Pending |
| Versioned | 1.3.3.002 | add db relationship table         | SQL  |              | Pending |
| Versioned | 1.3.3.003 | alter analysis unique constraint  | SQL  |              | Pending |
| Versioned | 1.3.3.004 | add synoynm indices cvtermsynonym | SQL  |              | Pending |
| Versioned | 1.3.3.005 | add type id 2 project table       | SQL  |              | Pending |
| Versioned | 1.3.3.006 | modify mage                       | SQL  |              | Pending |
| Versioned | 1.3.3.007 | fix search path                   | SQL  |              | Pending |
| Versioned | 1.3.3.008 | add is obsolete cell line table   | SQL  |              | Pending |
| Versioned | 1.3.3.009 | update analysis desc              | SQL  |              | Pending |
+-----------+-----------+-----------------------------------+------+--------------+---------+

```

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
✅ Using the makefile to build the image
✅ Running the image
✅ Using flyway inside the container on start

So next I tried to use the image to test a PR :-)
Based on the dockerfile I saw Chado was cloned at the root so I cd'd in and switched the branch to an existing PR. Then I tried using `flyway info` and ran found out it couldn't be used anywhere but the root directory.

Notes:
- We could use some docs related to how to use the docker to test a PR and inspect the schema.
- flyway only works if you're in the root directory. This is a pain if you need to change branches first.
- docs on using psql to actually check the schema would also be nice :-D especially if there were an alias so you can just use `psql` without args for those who don't read the docs ;-)

**Comment by spficklin** [comment]
Okay, I've made the changes you requested @laceysanderson .  You can now run Flyway from anywhere in the image (no need to be in the root folder) and the README has been updated to tell you how to find where the Chado repository is installed and how to run `psql`

I also make one additional change.  I changed the version of this Docker image to `1.31`  instead of `1.4` because I'm really confused about the versioning (see issue #130) and it doesn't make sense to have a `1.4` docker image of Chado if you then have to apply the 1.3.3_XXX Flyway fixes to it.....

**Review by scottcain — APPROVED** [review]
Very useful--thanks @spficklin !

**Review by laceysanderson — APPROVED** [review]
Awesome, thanks! This looks good to me and works as expected now :-) 👍

**Comment by laceysanderson** [comment]
Two reviews approving this change so this is ready to merge @scottcain 🎉  Thanks @spficklin this is going to make reviewing migration PRS so much easier!

**Pull request merged**
